# Generated by Django 2.2 on 2019-04-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ubigeo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('accion', models.CharField(choices=[('au', 'Aumento'), ('di', 'Disminuyo'), ('tr', 'Transfirio')], max_length=3)),
                ('cantidad', models.IntegerField(blank=True)),
                ('unidad', models.CharField(max_length=100)),
                ('al_destino', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='inventario.Almacen')),
                ('al_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='inventario.Almacen')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.ProdcutoVariacion')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField(blank=True)),
                ('unidad', models.CharField(blank=True, max_length=200)),
                ('almacen', models.CharField(blank=True, max_length=100)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Movimiento')),
                ('producto_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.ProdcutoVariacion')),
            ],
        ),
    ]
